#!/bin/bash
#http://public-dns.tk/nameserver/my.txt
srcfile=$PWD/dnslist
#mkdir dnsselect 1>/dev/null 2>&1
timesdns=`cat $srcfile|wc -l`
country=($(awk '{print $1}' $srcfile))

tmp_fifofile="/tmp/$$.fifo"
mkfifo $tmp_fifofile         
exec 6<>$tmp_fifofile      
rm $tmp_fifofile
thread=10 # 此处定义线程数
for ((i=0;i<$thread;i++));do
echo
done >&6 # 事实上就是在fd6中放置了$thread个回车符

for((x=0;x<$timesdns;x++));do
read -u6
{	
	curl http://public-dns.info/nameserver/${country[x]}.json -o ./${country[x]}.json -s
	echo >&6 
}&
done
wait
exec 6>&- 
echo "获取结束,文档保存于./dnsselect目录下"
