name: Daily Verify DNS
on:
  schedule:
    - cron: '0 */3 * * *' # 每 3 小时运行一次 (UTC 时间)
  workflow_dispatch:     # 可选：允许手动触发

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 需要完整提交历史
          
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dnsutils jq netcat-openbsd
        
      - name: Run Verification
        run: |
          chmod +x scripts/verify_dns.sh
          ./scripts/verify_dns.sh
          
      - name: Commit Verified Data
        run: |
          git config --global user.name "doroscn"
          git config --global user.email "jash.zheng@gmail.com"
          git add dnsselect/*.json scripts/state/validation_status.json
          git commit -m "Automatically update validation data: $(date +'%Y-%m-%d')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
