name: DNS Collector
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  collect-and-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dnsutils jq

      - name: Run DNS collection and verification
        run: |
          chmod +x scripts/dns-collect.sh
          ./scripts/dns-collect.sh

      - name: Commit updated DNS data
        run: |
          git config --global jash.zheng@gmail.com "GitHub Actions"
          git config --global jash.zheng@gmail.com "actions@github.com"
          git add dnsselect/*.json
          git commit -m "Auto-update DNS data"
          git push
