name: Manual Collect DNS Data
on:
  workflow_dispatch:  # 仅手动触发

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Collection Script
        run: |
          chmod +x scripts/collect_dns.sh
          ./scripts/collect_dns.sh
      - name: Commit Collected Data
        run: |
          git add dnsselect/*.json
          git commit -m "手动更新国家DNS数据" || echo "无新数据"
          git push
